### ISSUE TITLE
Release colorblindr on CRAN

### ISSUE THREAD

**Issue by clauswilke** [clauswilke/colorblindr#14]
We should prepare a proper release. What is still needed? Here are some things I can think about:

- [ ] Move github repo to wilkelab. This allows us to add a pkgdown website and host it under wilkelab.org, as in https://wilkelab.org/isoband/ or https://wilkelab.org/ungeviz/.
- [ ] Check dependencies. Do we depend on the development version of cowplot, as the readme states? The listed dependency is >0.8.0, and the version on CRAN is 0.9.4, so this should be fine.
- [ ] No packages other than base R should be listed under "Depends". All other dependencies should be listed under "Imports".
- [ ] Update installation instructions in the readme.
- [ ] Review all vignettes.
- [ ] Remove the ggplot2 color scales vignette. It is outdated and there are other packages now that focus specifically on color scales, e.g. [paletteer](https://CRAN.R-project.org/package=paletteer).

Something else?

**Comment by mine-cetinkaya-rundel** [comment]
Is this still in the plans? I use this package in my work pretty regularly and I'd like to teach it as well in my intro data science course, but for that course, I've mostly been sticking to packages on CRAN. If there is no plan to release it in the near future, is there another package you recommend for accessible color scales? [scico](https://github.com/thomasp85/scico) is a great alternative but doesn't work for discrete scales.

**Comment by clauswilke** [comment]
No, I should close the issue. Most of the main features have been integrated into places where they fit better, in particular the colorvision deficiency simulations into the colorspace package: https://colorspace.r-forge.r-project.org/articles/color_vision_deficiency.html

For discrete palettes, I no longer believe that a built-in scale function is the right approach. It's better to set colors manually. However, if you want a simple scale function, use `scale_color_colorblind()` from the ggthemes package.

You can see my slides on this topic here: 
https://wilkelab.org/DSC385/slides/color-scales.html#43
