### ISSUE TITLE
Feature request: Separate palettes from colorblind functionality

### ISSUE THREAD

**Issue by burgerga** [clauswilke/colorblindr#8]
Thanks for making this available, I would love (my colleagues) to use the information in http://serialmentor.com/dataviz/ to create better plots AND use colorblind-friendly colors. Is it possible to separate the actual color palettes from the colorblind simulation functionality? That way they can use those palettes without having to (know how to) use `devtools` to install development packages.

**Comment by clauswilke** [comment]
We have every intention to submit this package to CRAN. However, we have to wait until the next version of colorspace is submitted, and this is mostly outside of our control. The color palette functions in colorblindr make use of new colorspace features and therefore can't be published on CRAN without colorspace being updated on CRAN.

In the mean time, you can use `scale_color_colorblind()` from the ggthemes package. It is essentially the same color scale, just the colors are in different order.
